# Pipeline for check to build ios app..
pipelines:
  pull-requests:
    '**':
      - parallel: 
        - step:
            name: Info about build
            runs-on:
              - macos
            script:
              - echo "Хеш коммита сборки - $BITBUCKET_COMMIT"
              - echo "Ветка источник - $BITBUCKET_BRANCH"
              - echo "Ветка назначения - $BITBUCKET_PR_DESTINATION_BRANCH"
      - step:
            name: Build
            runs-on:
              - macos
            script:
              - xcodebuild -workspace Zveron.xcworkspace -scheme ConsumerApp test -destination "platform=iOS Simulator,name=iPhone 14"
      - step:
            name: Build specialist
            runs-on:
              - macos
            script:
              - xcodebuild -workspace Zveron.xcworkspace -scheme SpecialistApp test -destination "platform=iOS Simulator,name=iPhone 14"

  branches:
    master:
      - parallel: 
        - step:
            name: Info about build
            runs-on:
              - macos
            script:
              - echo "Хеш коммита сборки - $BITBUCKET_COMMIT"
              - echo "Ветка сборки - $BITBUCKET_BRANCH"
      - step:
            name: Build
            runs-on:
              - macos
            script:
              - xcodebuild -workspace Zveron.xcworkspace -scheme ConsumerApp test -destination "platform=iOS Simulator,name=iPhone 14"

      - step:
            name: Build specialist
            runs-on:
              - macos
            script:
              - xcodebuild -workspace Zveron.xcworkspace -scheme SpecialistApp test -destination "platform=iOS Simulator,name=iPhone 14"
