
name: Swift

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
 test:
   name: Test
   runs-on: macOS-latest
   
   strategy:
       matrix:
         destination: ['platform=iOS Simulator,name=iPhone 14']
   env: 
     destination: ${{ matrix.destination }}
   
   steps:
     — uses: actions/checkout@v3
     — name: Print Info
       run: echo "The GitHub Actor's username is: $GITHUB_ACTOR"
       
     — name: Run build and test for CONSUMER_APP
       run: xcodebuild -workspace Zveron.xcworkspace -scheme ConsumerApp test -destination "${destination}"
 
     — name: Run build and test for SPECIALIST_APP
       run: xcodebuild -workspace Zveron.xcworkspace -scheme SpecialistApp test -destination "${destination}"

        
        
